/*
Copyright (C) 1997-2001 Id Software, Inc.

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  

See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

*/
/*
==============================================================================

BERSERK

==============================================================================
*/

/* already inlined above: game/g_local.h */
/* ============ begin inlined header: game/m_berserk.h ============ */
/*
Copyright (C) 1997-2001 Id Software, Inc.

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  

See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

*/
// G:\quake2\baseq2\models/monsters/berserk

// This file generated by ModelGen - Do NOT Modify

#define FRAME_stand1          	0
#define FRAME_stand2          	1
#define FRAME_stand3          	2
#define FRAME_stand4          	3
#define FRAME_stand5          	4
#define FRAME_standb1         	5
#define FRAME_standb2         	6
#define FRAME_standb3         	7
#define FRAME_standb4         	8
#define FRAME_standb5         	9
#define FRAME_standb6         	10
#define FRAME_standb7         	11
#define FRAME_standb8         	12
#define FRAME_standb9         	13
#define FRAME_standb10        	14
#define FRAME_standb11        	15
#define FRAME_standb12        	16
#define FRAME_standb13        	17
#define FRAME_standb14        	18
#define FRAME_standb15        	19
#define FRAME_standb16        	20
#define FRAME_standb17        	21
#define FRAME_standb18        	22
#define FRAME_standb19        	23
#define FRAME_standb20        	24
#define FRAME_walkc1          	25
#define FRAME_walkc2          	26
#define FRAME_walkc3          	27
#define FRAME_walkc4          	28
#define FRAME_walkc5          	29
#define FRAME_walkc6          	30
#define FRAME_walkc7          	31
#define FRAME_walkc8          	32
#define FRAME_walkc9          	33
#define FRAME_walkc10         	34
#define FRAME_walkc11         	35
#define FRAME_run1            	36
#define FRAME_run2            	37
#define FRAME_run3            	38
#define FRAME_run4            	39
#define FRAME_run5            	40
#define FRAME_run6            	41
#define FRAME_att_a1          	42
#define FRAME_att_a2          	43
#define FRAME_att_a3          	44
#define FRAME_att_a4          	45
#define FRAME_att_a5          	46
#define FRAME_att_a6          	47
#define FRAME_att_a7          	48
#define FRAME_att_a8          	49
#define FRAME_att_a9          	50
#define FRAME_att_a10         	51
#define FRAME_att_a11         	52
#define FRAME_att_a12         	53
#define FRAME_att_a13         	54
#define FRAME_att_b1          	55
#define FRAME_att_b2          	56
#define FRAME_att_b3          	57
#define FRAME_att_b4          	58
#define FRAME_att_b5          	59
#define FRAME_att_b6          	60
#define FRAME_att_b7          	61
#define FRAME_att_b8          	62
#define FRAME_att_b9          	63
#define FRAME_att_b10         	64
#define FRAME_att_b11         	65
#define FRAME_att_b12         	66
#define FRAME_att_b13         	67
#define FRAME_att_b14         	68
#define FRAME_att_b15         	69
#define FRAME_att_b16         	70
#define FRAME_att_b17         	71
#define FRAME_att_b18         	72
#define FRAME_att_b19         	73
#define FRAME_att_b20         	74
#define FRAME_att_b21         	75
#define FRAME_att_c1          	76
#define FRAME_att_c2          	77
#define FRAME_att_c3          	78
#define FRAME_att_c4          	79
#define FRAME_att_c5          	80
#define FRAME_att_c6          	81
#define FRAME_att_c7          	82
#define FRAME_att_c8          	83
#define FRAME_att_c9          	84
#define FRAME_att_c10         	85
#define FRAME_att_c11         	86
#define FRAME_att_c12         	87
#define FRAME_att_c13         	88
#define FRAME_att_c14         	89
#define FRAME_att_c15         	90
#define FRAME_att_c16         	91
#define FRAME_att_c17         	92
#define FRAME_att_c18         	93
#define FRAME_att_c19         	94
#define FRAME_att_c20         	95
#define FRAME_att_c21         	96
#define FRAME_att_c22         	97
#define FRAME_att_c23         	98
#define FRAME_att_c24         	99
#define FRAME_att_c25         	100
#define FRAME_att_c26         	101
#define FRAME_att_c27         	102
#define FRAME_att_c28         	103
#define FRAME_att_c29         	104
#define FRAME_att_c30         	105
#define FRAME_att_c31         	106
#define FRAME_att_c32         	107
#define FRAME_att_c33         	108
#define FRAME_att_c34         	109
#define FRAME_r_att1          	110
#define FRAME_r_att2          	111
#define FRAME_r_att3          	112
#define FRAME_r_att4          	113
#define FRAME_r_att5          	114
#define FRAME_r_att6          	115
#define FRAME_r_att7          	116
#define FRAME_r_att8          	117
#define FRAME_r_att9          	118
#define FRAME_r_att10         	119
#define FRAME_r_att11         	120
#define FRAME_r_att12         	121
#define FRAME_r_att13         	122
#define FRAME_r_att14         	123
#define FRAME_r_att15         	124
#define FRAME_r_att16         	125
#define FRAME_r_att17         	126
#define FRAME_r_att18         	127
#define FRAME_r_attb1         	128
#define FRAME_r_attb2         	129
#define FRAME_r_attb3         	130
#define FRAME_r_attb4         	131
#define FRAME_r_attb5         	132
#define FRAME_r_attb6         	133
#define FRAME_r_attb7         	134
#define FRAME_r_attb8         	135
#define FRAME_r_attb9         	136
#define FRAME_r_attb10        	137
#define FRAME_r_attb11        	138
#define FRAME_r_attb12        	139
#define FRAME_r_attb13        	140
#define FRAME_r_attb14        	141
#define FRAME_r_attb15        	142
#define FRAME_r_attb16        	143
#define FRAME_r_attb17        	144
#define FRAME_r_attb18        	145
#define FRAME_slam1           	146
#define FRAME_slam2           	147
#define FRAME_slam3           	148
#define FRAME_slam4           	149
#define FRAME_slam5           	150
#define FRAME_slam6           	151
#define FRAME_slam7           	152
#define FRAME_slam8           	153
#define FRAME_slam9           	154
#define FRAME_slam10          	155
#define FRAME_slam11          	156
#define FRAME_slam12          	157
#define FRAME_slam13          	158
#define FRAME_slam14          	159
#define FRAME_slam15          	160
#define FRAME_slam16          	161
#define FRAME_slam17          	162
#define FRAME_slam18          	163
#define FRAME_slam19          	164
#define FRAME_slam20          	165
#define FRAME_slam21          	166
#define FRAME_slam22          	167
#define FRAME_slam23          	168
#define FRAME_duck1           	169
#define FRAME_duck2           	170
#define FRAME_duck3           	171
#define FRAME_duck4           	172
#define FRAME_duck5           	173
#define FRAME_duck6           	174
#define FRAME_duck7           	175
#define FRAME_duck8           	176
#define FRAME_duck9           	177
#define FRAME_duck10          	178
#define FRAME_fall1           	179
#define FRAME_fall2           	180
#define FRAME_fall3           	181
#define FRAME_fall4           	182
#define FRAME_fall5           	183
#define FRAME_fall6           	184
#define FRAME_fall7           	185
#define FRAME_fall8           	186
#define FRAME_fall9           	187
#define FRAME_fall10          	188
#define FRAME_fall11          	189
#define FRAME_fall12          	190
#define FRAME_fall13          	191
#define FRAME_fall14          	192
#define FRAME_fall15          	193
#define FRAME_fall16          	194
#define FRAME_fall17          	195
#define FRAME_fall18          	196
#define FRAME_fall19          	197
#define FRAME_fall20          	198
#define FRAME_painc1          	199
#define FRAME_painc2          	200
#define FRAME_painc3          	201
#define FRAME_painc4          	202
#define FRAME_painb1          	203
#define FRAME_painb2          	204
#define FRAME_painb3          	205
#define FRAME_painb4          	206
#define FRAME_painb5          	207
#define FRAME_painb6          	208
#define FRAME_painb7          	209
#define FRAME_painb8          	210
#define FRAME_painb9          	211
#define FRAME_painb10         	212
#define FRAME_painb11         	213
#define FRAME_painb12         	214
#define FRAME_painb13         	215
#define FRAME_painb14         	216
#define FRAME_painb15         	217
#define FRAME_painb16         	218
#define FRAME_painb17         	219
#define FRAME_painb18         	220
#define FRAME_painb19         	221
#define FRAME_painb20         	222
#define FRAME_death1          	223
#define FRAME_death2          	224
#define FRAME_death3          	225
#define FRAME_death4          	226
#define FRAME_death5          	227
#define FRAME_death6          	228
#define FRAME_death7          	229
#define FRAME_death8          	230
#define FRAME_death9          	231
#define FRAME_death10         	232
#define FRAME_death11         	233
#define FRAME_death12         	234
#define FRAME_death13         	235
#define FRAME_deathc1         	236
#define FRAME_deathc2         	237
#define FRAME_deathc3         	238
#define FRAME_deathc4         	239
#define FRAME_deathc5         	240
#define FRAME_deathc6         	241
#define FRAME_deathc7         	242
#define FRAME_deathc8         	243

#define MODEL_SCALE		1.000000
/* ============ end inlined header: game/m_berserk.h ============ */


static int sound_pain;
static int sound_die;
static int sound_idle;
static int sound_punch;
static int sound_sight;
static int sound_search;

void berserk_sight (edict_t *self, edict_t *other)
{
	gi.sound (self, CHAN_VOICE, sound_sight, 1, ATTN_NORM, 0);
}

void berserk_search (edict_t *self)
{
	gi.sound (self, CHAN_VOICE, sound_search, 1, ATTN_NORM, 0);
}


void berserk_fidget (edict_t *self);
mframe_t berserk_frames_stand [] =
{
	ai_stand, 0, berserk_fidget,
	ai_stand, 0, NULL,
	ai_stand, 0, NULL,
	ai_stand, 0, NULL,
	ai_stand, 0, NULL
};
mmove_t berserk_move_stand = {FRAME_stand1, FRAME_stand5, berserk_frames_stand, NULL};

void berserk_stand (edict_t *self)
{
	self->monsterinfo.currentmove = &berserk_move_stand;
}

mframe_t berserk_frames_stand_fidget [] =
{
	ai_stand, 0, NULL,
	ai_stand, 0, NULL,
	ai_stand, 0, NULL,
	ai_stand, 0, NULL,
	ai_stand, 0, NULL,
	ai_stand, 0, NULL,
	ai_stand, 0, NULL,
	ai_stand, 0, NULL,
	ai_stand, 0, NULL,
	ai_stand, 0, NULL,
	ai_stand, 0, NULL,
	ai_stand, 0, NULL,
	ai_stand, 0, NULL,
	ai_stand, 0, NULL,
	ai_stand, 0, NULL,
	ai_stand, 0, NULL,
	ai_stand, 0, NULL,
	ai_stand, 0, NULL,
	ai_stand, 0, NULL,
	ai_stand, 0, NULL
};
mmove_t berserk_move_stand_fidget = {FRAME_standb1, FRAME_standb20, berserk_frames_stand_fidget, berserk_stand};

void berserk_fidget (edict_t *self)
{
	if (self->monsterinfo.aiflags & AI_STAND_GROUND)
		return;
	if (random() > 0.15)
		return;

	self->monsterinfo.currentmove = &berserk_move_stand_fidget;
	gi.sound (self, CHAN_WEAPON, sound_idle, 1, ATTN_IDLE, 0);
}


mframe_t berserk_frames_walk [] =
{
	ai_walk, 9.1, NULL,
	ai_walk, 6.3, NULL,
	ai_walk, 4.9, NULL,
	ai_walk, 6.7, NULL,
	ai_walk, 6.0, NULL,
	ai_walk, 8.2, NULL,
	ai_walk, 7.2, NULL,
	ai_walk, 6.1, NULL,
	ai_walk, 4.9, NULL,
	ai_walk, 4.7, NULL,
	ai_walk, 4.7, NULL,
	ai_walk, 4.8, NULL
};
mmove_t berserk_move_walk = {FRAME_walkc1, FRAME_walkc11, berserk_frames_walk, NULL};

void berserk_walk (edict_t *self)
{
	self->monsterinfo.currentmove = &berserk_move_walk;
}

/*

  *****************************
  SKIPPED THIS FOR NOW!
  *****************************

   Running -> Arm raised in air

void()	berserk_runb1	=[	$r_att1 ,	berserk_runb2	] {ai_run(21);};
void()	berserk_runb2	=[	$r_att2 ,	berserk_runb3	] {ai_run(11);};
void()	berserk_runb3	=[	$r_att3 ,	berserk_runb4	] {ai_run(21);};
void()	berserk_runb4	=[	$r_att4 ,	berserk_runb5	] {ai_run(25);};
void()	berserk_runb5	=[	$r_att5 ,	berserk_runb6	] {ai_run(18);};
void()	berserk_runb6	=[	$r_att6 ,	berserk_runb7	] {ai_run(19);};
// running with arm in air : start loop
void()	berserk_runb7	=[	$r_att7 ,	berserk_runb8	] {ai_run(21);};
void()	berserk_runb8	=[	$r_att8 ,	berserk_runb9	] {ai_run(11);};
void()	berserk_runb9	=[	$r_att9 ,	berserk_runb10	] {ai_run(21);};
void()	berserk_runb10	=[	$r_att10 ,	berserk_runb11	] {ai_run(25);};
void()	berserk_runb11	=[	$r_att11 ,	berserk_runb12	] {ai_run(18);};
void()	berserk_runb12	=[	$r_att12 ,	berserk_runb7	] {ai_run(19);};
// running with arm in air : end loop
*/


mframe_t berserk_frames_run1 [] =
{
	ai_run, 21, NULL,
	ai_run, 11, NULL,
	ai_run, 21, NULL,
	ai_run, 25, NULL,
	ai_run, 18, NULL,
	ai_run, 19, NULL
};
mmove_t berserk_move_run1 = {FRAME_run1, FRAME_run6, berserk_frames_run1, NULL};

void berserk_run (edict_t *self)
{
	if (self->monsterinfo.aiflags & AI_STAND_GROUND)
		self->monsterinfo.currentmove = &berserk_move_stand;
	else
		self->monsterinfo.currentmove = &berserk_move_run1;
}


void berserk_attack_spike (edict_t *self)
{
	static	vec3_t	aim = {MELEE_DISTANCE, 0, -24};
	fire_hit (self, aim, (15 + (rand() % 6)), 400);		//	Faster attack -- upwards and backwards
}


void berserk_swing (edict_t *self)
{
	gi.sound (self, CHAN_WEAPON, sound_punch, 1, ATTN_NORM, 0);
}

mframe_t berserk_frames_attack_spike [] =
{
		ai_charge, 0, NULL,
		ai_charge, 0, NULL,
		ai_charge, 0, berserk_swing,
		ai_charge, 0, berserk_attack_spike,
		ai_charge, 0, NULL,
		ai_charge, 0, NULL,
		ai_charge, 0, NULL,
		ai_charge, 0, NULL
};
mmove_t berserk_move_attack_spike = {FRAME_att_c1, FRAME_att_c8, berserk_frames_attack_spike, berserk_run};


void berserk_attack_club (edict_t *self)
{
	vec3_t	aim;

	VectorSet (aim, MELEE_DISTANCE, self->mins[0], -4);
	fire_hit (self, aim, (5 + (rand() % 6)), 400);		// Slower attack
}

mframe_t berserk_frames_attack_club [] =
{	
	ai_charge, 0, NULL,
	ai_charge, 0, NULL,
	ai_charge, 0, NULL,
	ai_charge, 0, NULL,
	ai_charge, 0, berserk_swing,
	ai_charge, 0, NULL,
	ai_charge, 0, NULL,
	ai_charge, 0, NULL,
	ai_charge, 0, berserk_attack_club,
	ai_charge, 0, NULL,
	ai_charge, 0, NULL,
	ai_charge, 0, NULL
};
mmove_t berserk_move_attack_club = {FRAME_att_c9, FRAME_att_c20, berserk_frames_attack_club, berserk_run};


void berserk_strike (edict_t *self)
{
	//FIXME play impact sound
}


mframe_t berserk_frames_attack_strike [] =
{
	ai_move, 0, NULL,
	ai_move, 0, NULL,
	ai_move, 0, NULL,
	ai_move, 0, berserk_swing,
	ai_move, 0, NULL,
	ai_move, 0, NULL,
	ai_move, 0, NULL,
	ai_move, 0, berserk_strike,
	ai_move, 0, NULL,
	ai_move, 0, NULL,
	ai_move, 0, NULL,
	ai_move, 0, NULL,
	ai_move, 9.7, NULL,
	ai_move, 13.6, NULL
};
	
mmove_t berserk_move_attack_strike = {FRAME_att_c21, FRAME_att_c34, berserk_frames_attack_strike, berserk_run};


void berserk_melee (edict_t *self)
{
	if ((rand() % 2) == 0)
		self->monsterinfo.currentmove = &berserk_move_attack_spike;
	else
		self->monsterinfo.currentmove = &berserk_move_attack_club;
}


/*
void() 	berserk_atke1	=[	$r_attb1,	berserk_atke2	] {ai_run(9);};
void() 	berserk_atke2	=[	$r_attb2,	berserk_atke3	] {ai_run(6);};
void() 	berserk_atke3	=[	$r_attb3,	berserk_atke4	] {ai_run(18.4);};
void() 	berserk_atke4	=[	$r_attb4,	berserk_atke5	] {ai_run(25);};
void() 	berserk_atke5	=[	$r_attb5,	berserk_atke6	] {ai_run(14);};
void() 	berserk_atke6	=[	$r_attb6,	berserk_atke7	] {ai_run(20);};
void() 	berserk_atke7	=[	$r_attb7,	berserk_atke8	] {ai_run(8.5);};
void() 	berserk_atke8	=[	$r_attb8,	berserk_atke9	] {ai_run(3);};
void() 	berserk_atke9	=[	$r_attb9,	berserk_atke10	] {ai_run(17.5);};
void() 	berserk_atke10	=[	$r_attb10,	berserk_atke11	] {ai_run(17);};
void() 	berserk_atke11	=[	$r_attb11,	berserk_atke12	] {ai_run(9);};
void() 	berserk_atke12	=[	$r_attb12,	berserk_atke13	] {ai_run(25);};
void() 	berserk_atke13	=[	$r_attb13,	berserk_atke14	] {ai_run(3.7);};
void() 	berserk_atke14	=[	$r_attb14,	berserk_atke15	] {ai_run(2.6);};
void() 	berserk_atke15	=[	$r_attb15,	berserk_atke16	] {ai_run(19);};
void() 	berserk_atke16	=[	$r_attb16,	berserk_atke17	] {ai_run(25);};
void() 	berserk_atke17	=[	$r_attb17,	berserk_atke18	] {ai_run(19.6);};
void() 	berserk_atke18	=[	$r_attb18,	berserk_run1	] {ai_run(7.8);};
*/


mframe_t berserk_frames_pain1 [] =
{
	ai_move, 0, NULL,
	ai_move, 0, NULL,
	ai_move, 0, NULL,
	ai_move, 0, NULL
};
mmove_t berserk_move_pain1 = {FRAME_painc1, FRAME_painc4, berserk_frames_pain1, berserk_run};


mframe_t berserk_frames_pain2 [] =
{
	ai_move, 0, NULL,
	ai_move, 0, NULL,
	ai_move, 0, NULL,
	ai_move, 0, NULL,
	ai_move, 0, NULL,
	ai_move, 0, NULL,
	ai_move, 0, NULL,
	ai_move, 0, NULL,
	ai_move, 0, NULL,
	ai_move, 0, NULL,
	ai_move, 0, NULL,
	ai_move, 0, NULL,
	ai_move, 0, NULL,
	ai_move, 0, NULL,
	ai_move, 0, NULL,
	ai_move, 0, NULL,
	ai_move, 0, NULL,
	ai_move, 0, NULL,
	ai_move, 0, NULL,
	ai_move, 0, NULL
};
mmove_t berserk_move_pain2 = {FRAME_painb1, FRAME_painb20, berserk_frames_pain2, berserk_run};

void berserk_pain (edict_t *self, edict_t *other, float kick, int damage)
{
	if (self->health < (self->max_health / 2))
		self->s.skinnum = 1;

	if (level.time < self->pain_debounce_time)
		return;

	self->pain_debounce_time = level.time + 3;
	gi.sound (self, CHAN_VOICE, sound_pain, 1, ATTN_NORM, 0);

	if (skill->value == 3)
		return;		// no pain anims in nightmare

	if ((damage < 20) || (random() < 0.5))
		self->monsterinfo.currentmove = &berserk_move_pain1;
	else
		self->monsterinfo.currentmove = &berserk_move_pain2;
}


void berserk_dead (edict_t *self)
{
	VectorSet (self->mins, -16, -16, -24);
	VectorSet (self->maxs, 16, 16, -8);
	self->movetype = MOVETYPE_TOSS;
	self->svflags |= SVF_DEADMONSTER;
	self->nextthink = 0;
	gi.linkentity (self);
}


mframe_t berserk_frames_death1 [] =
{
	ai_move, 0, NULL,
	ai_move, 0, NULL,
	ai_move, 0, NULL,
	ai_move, 0, NULL,
	ai_move, 0, NULL,
	ai_move, 0, NULL,
	ai_move, 0, NULL,
	ai_move, 0, NULL,
	ai_move, 0, NULL,
	ai_move, 0, NULL,
	ai_move, 0, NULL,
	ai_move, 0, NULL,
	ai_move, 0, NULL
	
};
mmove_t berserk_move_death1 = {FRAME_death1, FRAME_death13, berserk_frames_death1, berserk_dead};


mframe_t berserk_frames_death2 [] =
{
	ai_move, 0, NULL,
	ai_move, 0, NULL,
	ai_move, 0, NULL,
	ai_move, 0, NULL,
	ai_move, 0, NULL,
	ai_move, 0, NULL,
	ai_move, 0, NULL,
	ai_move, 0, NULL
};
mmove_t berserk_move_death2 = {FRAME_deathc1, FRAME_deathc8, berserk_frames_death2, berserk_dead};


void berserk_die (edict_t *self, edict_t *inflictor, edict_t *attacker, int damage, vec3_t point)
{
	int		n;

	if (self->health <= self->gib_health)
	{
		gi.sound (self, CHAN_VOICE, gi.soundindex ("misc/udeath.wav"), 1, ATTN_NORM, 0);
		for (n= 0; n < 2; n++)
			ThrowGib (self, "models/objects/gibs/bone/tris.md2", damage, GIB_ORGANIC);
		for (n= 0; n < 4; n++)
			ThrowGib (self, "models/objects/gibs/sm_meat/tris.md2", damage, GIB_ORGANIC);
		ThrowHead (self, "models/objects/gibs/head2/tris.md2", damage, GIB_ORGANIC);
		self->deadflag = DEAD_DEAD;
		return;
	}

	if (self->deadflag == DEAD_DEAD)
		return;

	gi.sound (self, CHAN_VOICE, sound_die, 1, ATTN_NORM, 0);
	self->deadflag = DEAD_DEAD;
	self->takedamage = DAMAGE_YES;

	if (damage >= 50)
		self->monsterinfo.currentmove = &berserk_move_death1;
	else
		self->monsterinfo.currentmove = &berserk_move_death2;
}


/*QUAKED monster_berserk (1 .5 0) (-16 -16 -24) (16 16 32) Ambush Trigger_Spawn Sight
*/
void SP_monster_berserk (edict_t *self)
{
	if (deathmatch->value)
	{
		G_FreeEdict (self);
		return;
	}

	// pre-caches
	sound_pain  = gi.soundindex ("berserk/berpain2.wav");
	sound_die   = gi.soundindex ("berserk/berdeth2.wav");
	sound_idle  = gi.soundindex ("berserk/beridle1.wav");
	sound_punch = gi.soundindex ("berserk/attack.wav");
	sound_search = gi.soundindex ("berserk/bersrch1.wav");
	sound_sight = gi.soundindex ("berserk/sight.wav");

	self->s.modelindex = gi.modelindex("models/monsters/berserk/tris.md2");
	VectorSet (self->mins, -16, -16, -24);
	VectorSet (self->maxs, 16, 16, 32);
	self->movetype = MOVETYPE_STEP;
	self->solid = SOLID_BBOX;

	self->health = 240;
	self->gib_health = -60;
	self->mass = 250;

	self->pain = berserk_pain;
	self->die = berserk_die;

	self->monsterinfo.stand = berserk_stand;
	self->monsterinfo.walk = berserk_walk;
	self->monsterinfo.run = berserk_run;
	self->monsterinfo.dodge = NULL;
	self->monsterinfo.attack = NULL;
	self->monsterinfo.melee = berserk_melee;
	self->monsterinfo.sight = berserk_sight;
	self->monsterinfo.search = berserk_search;

	self->monsterinfo.currentmove = &berserk_move_stand;
	self->monsterinfo.scale = MODEL_SCALE;

	gi.linkentity (self);

	walkmonster_start (self);
}
